using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;
using Content.Client.PDA.Messenger;
namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;
        // <------ PDA Messenger ------>
        public const int MessengerView = 4;
        public const int ConversationView = 5;

        private int _currentView;
        // <------ PDA Messenger Tests------>
        //private List<string> testRecipientList = new List<string> { "bob", "Mary", "Geraldo" };

        private List<PdaMessengerUiState.PdaMessage> testMessages = new List<PdaMessengerUiState.PdaMessage>()
        {
            new PdaMessengerUiState.PdaMessage("bob", "Howdy"),
            new PdaMessengerUiState.PdaMessage("mary", "Yo"),
            new PdaMessengerUiState.PdaMessage("Geraldo", "Hello")
        };

        private List<PdaMessengerUiState.PdaConversation> testConversations =
            new List<PdaMessengerUiState.PdaConversation>() { };

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action<Dictionary<string, string>>? OnNamePressed;

        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            PopulateTestConversations();
            PopulateConversationContainer(new PdaMessengerUiState(testConversations).PdaConversations);


            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));
            MessageButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/message.png"));


            HomeButton.OnPressed += _ => ToHomeScreen();
            MessageButton.OnPressed += _ => ToMessageScreen();
            CreateMessageButton.OnPressed += _ => ToConversationScreen();

            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;
                MessageButton.IsCurrent = false;

                ChangeView(ProgramListView);
            };


            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;
                MessageButton.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;
                MessageButton.IsCurrent = false;

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };


            HideAllViews();
            ToHomeScreen();
        }

        public void PopulateTestConversations()
        {
            foreach (PdaMessengerUiState.PdaMessage message in testMessages)
            {
                testConversations.Add(new PdaMessengerUiState.PdaConversation(message));
            }
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;
            PopulateRecipientList(state.KnownPDAMessengers);

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", state.PdaOwnerInfo.ActualOwnerName)));
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown")),
                    ("jobTitle", state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned"))));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", state.StationName ?? Loc.GetString("comp-pda-ui-unknown"))));

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", Loc.GetString(alertLevelKey))
            ));

            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", Loc.GetString($"{alertLevelKey}-instructions")))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            ProgramList.RemoveAllChildren();

            if (programs.Count == 0)
            {
                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });

                return;
            }

            var row = CreateProgramListRow();
            var itemCount = 1;
            ProgramList.AddChild(row);

            foreach (var (uid, component) in programs)
            {
                //Create a new row every second program item starting from the first
                if (itemCount % 2 != 0)
                {
                    row = CreateProgramListRow();
                    ProgramList.AddChild(row);
                }

                var item = new PdaProgramItem();

                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);

                item.OnPressed += _ => OnProgramItemPressed?.Invoke(uid);

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                        break;
                }

                item.ProgramName.Text = Loc.GetString(component.ProgramName);
                item.SetHeight = 20;
                row.AddChild(item);

                itemCount++;
            }

            //Add a filler item to the last row when it only contains one item
            if (itemCount % 2 == 0)
                row.AddChild(new Control() { HorizontalExpand = true });
        }

        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = false;

            ChangeView(HomeView);
        }

        public void ToMessageScreen()
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = true;

            ChangeView(MessengerView);

        }

        public void ToConversationScreen()
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = true;

            ChangeView(ConversationView);
        }

        public void PopulateRecipientList(Dictionary<string, string> recipientList)
        {
            foreach (var recipient in recipientList)
            {
                var row = new BoxContainer();
                row.HorizontalExpand = true;
                row.Margin = new Thickness(4);

                var label = new Button();
                label.Text = recipient.Value;
                label.HorizontalExpand = true;
                label.ClipText = true;
                label.Name = recipient.Key;
                label.OnPressed += _ =>
                    OnNamePressed?.Invoke(new Dictionary<string, string>() { {label.Name, label.Text} });
                row.AddChild(label);
                RecipientList.AddChild(row);
            }
        }

        public void PopulateConversationContainer(List<PdaMessengerUiState.PdaConversation> conversations)
        {
            ConversationContainer.RemoveAllChildren();
            ConversationScrollContainer.HScrollEnabled = conversations.Count > 9;
            foreach (var conversation in conversations)
            {
                AddPdaMessage(conversation);
            }
        }

        public void UpdateRecipient(string address, string name)
        {
            RxCollapsibleBody.Visible = false;
            RxCollapsibleHeading.Title = name + "-" + address;
        }

        public void AddPdaMessage(PdaMessengerUiState.PdaConversation conversation)
        {
            var row = new BoxContainer();
            row.HorizontalExpand = true;
            row.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            row.Margin = new Thickness(4);

            var nameLabel = new Label();
            nameLabel.Text = conversation.Name;
            nameLabel.HorizontalExpand = false;
            nameLabel.SetWidth = 100f;
            nameLabel.ClipText = true;
            row.AddChild(nameLabel);

            var messageLabel = new Label();
            messageLabel.Text = conversation.LastMessage;
            messageLabel.HorizontalExpand = true;
            messageLabel.ClipText = true;
            row.AddChild(messageLabel);

            ConversationContainer.AddChild(row);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;
            MessageButton.IsCurrent = false;

            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private static BoxContainer CreateProgramListRow()
        {
            return new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
