using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;
using Content.Client.PDA.Messenger;
namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;
        private PdaMessengerUiState _state;

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;
        // <------ PDA Messenger ------>
        public const int MessengerView = 4;
        public const int ConversationView = 5;

        private int _currentView;
        // <------ PDA Messenger Tests------>
        //private List<string> testRecipientList = new List<string> { "bob", "Mary", "Geraldo" };

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action<string>? OnSendMessageButtonPressed;

        public event Action<List<PdaMessengerUiState.Recipient>>? OnNamePressed;

        public PdaMenu(PdaMessengerUiState state)
        {
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);
            _state = state;

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));
            MessageButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/message.png"));


            HomeButton.OnPressed += _ => ToHomeScreen();
            MessageButton.OnPressed += _ => ToMessageScreen();
            CreateMessageButton.OnPressed += _ => ToConversationScreen();
            MessageSendButton.OnPressed += _ => SendMessagePressed();
            SelectRecipientButton.OnPressed += _ => OnSelectRecipientButtonPressed();



            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;
                MessageButton.IsCurrent = false;

                ChangeView(ProgramListView);
            };


            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;
                MessageButton.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;
                MessageButton.IsCurrent = false;

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };


            HideAllViews();
            ToHomeScreen();
        }
        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", state.PdaOwnerInfo.ActualOwnerName)));
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown")),
                    ("jobTitle", state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned"))));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", state.StationName ?? Loc.GetString("comp-pda-ui-unknown"))));

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", Loc.GetString(alertLevelKey))
            ));

            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", Loc.GetString($"{alertLevelKey}-instructions")))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;

            PopulateRecipientList(state.KnownPDAMessengers);
            PopulateConversations(state.ConversationList);


        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            ProgramList.RemoveAllChildren();

            if (programs.Count == 0)
            {
                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });

                return;
            }

            var row = CreateProgramListRow();
            var itemCount = 1;
            ProgramList.AddChild(row);

            foreach (var (uid, component) in programs)
            {
                //Create a new row every second program item starting from the first
                if (itemCount % 2 != 0)
                {
                    row = CreateProgramListRow();
                    ProgramList.AddChild(row);
                }

                var item = new PdaProgramItem();

                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);

                item.OnPressed += _ => OnProgramItemPressed?.Invoke(uid);

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                        break;
                }

                item.ProgramName.Text = Loc.GetString(component.ProgramName);
                item.SetHeight = 20;
                row.AddChild(item);

                itemCount++;
            }

            //Add a filler item to the last row when it only contains one item
            if (itemCount % 2 == 0)
                row.AddChild(new Control() { HorizontalExpand = true });
        }

        public void SendMessagePressed()
        {
            if (_state.CurrentRecipients.Count < 1 || MessageInput.Text == "")
                return;
            OnSendMessageButtonPressed?.Invoke( MessageInput.Text);
            RecipientList.RemoveAllChildren();
            MessageInput.Clear();
            ToHomeScreen();
        }


        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = false;

            ChangeView(HomeView);
        }

        public void ToMessageScreen()
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = true;

            ChangeView(MessengerView);

        }

        public void ToConversationScreen()
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            MessageButton.IsCurrent = true;

            ChangeView(ConversationView);
        }

        public void PopulateRecipientList(Dictionary<string, string> recipientList)
        {
            if (!RxCollapsibleBody.Visible)
                return;
            RecipientList.RemoveAllChildren();
            _state.checkList.Clear();

            foreach (var recipient in recipientList)
            {
                var row = new BoxContainer();
                row.HorizontalExpand = true;
                row.Margin = new Thickness(4);

                var check = new CheckBox();
                check.HorizontalExpand = true;
                check.Name = recipient.Key;
                check.Label.Text = recipient.Value;
                check.OnToggled += _ =>
                {
                    if (_state.checkList.Contains(check))
                    {
                        _state.checkList.Remove(check);
                    }
                    else
                    {
                        _state.checkList.Add(check);
                    }
                };

                row.AddChild(check);
                RecipientList.AddChild(row);
            }

        }


        public void OnSelectRecipientButtonPressed()
        {
            List<PdaMessengerUiState.Recipient> recipients = new List<PdaMessengerUiState.Recipient>();
            foreach (CheckBox check in _state.checkList)
            {
                if (check.Text == null || check.Name == null)
                    return;
                recipients.Add(new PdaMessengerUiState.Recipient(check.Text, check.Name));
            }

            OnNamePressed?.Invoke(recipients);
        }

        public void PopulateConversations(List<PdaConversation> conversations)
        {
            if (conversations.Count < 1)
                return;

            ConversationContainer.RemoveAllChildren();
            ConversationScrollContainer.HScrollEnabled = conversations.Count > 9;
            foreach (var conversation in conversations)
            {
                AddPdaMessage(conversation);
            }
        }

        public void UpdateRecipient()
        {
            RxCollapsibleBody.Visible = !RxCollapsibleBody.Visible;
            //Adressees.RemoveAllChildren();
            foreach (PdaMessengerUiState.Recipient recipient in _state.CurrentRecipients)
            {
                var label = new Label();
                label.Text = recipient.Name;
                Adressees.AddChild(label);
            }
        }

        public void AddPdaMessage(PdaConversation conversation)
        {
            var row = new BoxContainer();
            row.Name = conversation.ConversationId;
            row.HorizontalExpand = true;
            row.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            row.Margin = new Thickness(4);

            var namePlate = new BoxContainer();
            namePlate.Orientation = BoxContainer.LayoutOrientation.Vertical;
            namePlate.HorizontalExpand = false;
            namePlate.SetWidth = 100f;

            foreach (var sender in conversation.RecipientList)
            {
                var senderLabel = new Label();
                senderLabel.Text = sender.Name;
                senderLabel.ClipText = true;
                namePlate.AddChild(senderLabel);
            }

            var lastMessageContainer = new BoxContainer();
            lastMessageContainer.HorizontalExpand = true;
            lastMessageContainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;

            var lastMessage = conversation.LastMessage();

            var lastMessageSender = new Label();
            lastMessageSender.HorizontalExpand = false;
            lastMessageSender.ClipText = true;
            lastMessageSender.SetWidth = 50f;
            lastMessageSender.Text = lastMessage.SenderName;

            var lastMessageLabel = new Label();
            lastMessageLabel.HorizontalExpand = true;
            lastMessageLabel.ClipText = true;
            lastMessageLabel.Text = lastMessage.Message;

            lastMessageContainer.AddChild(lastMessageSender);
            lastMessageContainer.AddChild(lastMessageLabel);

            row.AddChild(lastMessageContainer);
            row.AddChild(namePlate);

            ConversationContainer.AddChild(row);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;
            MessageButton.IsCurrent = false;

            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private static BoxContainer CreateProgramListRow()
        {
            return new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
